# Change these first
owner: Sergiop-Hackademy # Your GitHub organization or username, where this repository lives
repo: status_Parco # The name of this repository

sites:
  - name: Kraken
    url: https://kraken.parcoapp.com
  - name: Autotraze - dev
    url: https://net.env.parcoapp.com/autotraze
  - name: Campaigns - dev
    url: https://net.env.parcoapp.com/campaigns
  - name: Carts - dev
    url: https://net.env.parcoapp.com/carts/status
  - name: Hairs - dev
    url: https://net.env.parcoapp.com/hairs
  - name: News - dev
    url: https://net.env.parcoapp.com/news
  - name: Orchestrator - dev
    url: https://net.env.parcoapp.com/orchestrator
  - name: Promocao - dev
    url: https://net.env.parcoapp.com/promocao
  - name: Services - dev
    url: https://net.env.parcoapp.com/services
  - name: Users - dev
    url: https://net.env.parcoapp.com/users/status
  - name: Wallet - dev
    url: https://net.env.parcoapp.com/wallet
#   Prod  
  - name: Access Prod
    url: $SECRET_SITE_ACCESS_PROD
  - name: Autotraze Prod
    url: $SECRET_SITE_AUTOTRAZE_PROD
  - name: Campaigns Prod
    url: $SECRET_SITE_CAMPAIGNS_PROD
  - name: Carts Prod
    url: $SECRET_SITE_CARTS_PROD
  - name: Fidelity Prod
    url: $SECRET_SITE_FIDELITY_PROD
  - name: Ghostbuster Prod
    url: $SECRET_SITE_GHOSTBUSTER_PROD
  - name: Hairs Prod
    url: $SECRET_SITE_HAIRS_PROD
  - name: News Prod
    url: $SECRET_SITE_NEWS_PROD
  - name: Orchestrator Prod
    url: $SECRET_SITE_ORCHESTRATOR_PROD
  - name: Promocao Prod
    url: $SECRET_SITE_PROMOCAO_PROD
  - name: Tesseract - Prod
    url: $SECRET_SITE_TESSERACT_PROD
  - name: Service Prod
    url: $SECRET_SITE_SERVICE_PROD
  - name: User Prod
    url: $SECRET_SITE_USER_PROD
  - name: Wallet Prod
    url: $SECRET_SITE_WALLET_PROD



status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: /upptime

  baseUrl: /status_Parco
  logoUrl: https://cdn.parcoapp.com/assets/app/PARCO_LOGO_2.png
  name: Upptime
  introTitle: "**Upptime** pagina de estatus de ParcoApp"
  introMessage: Cualquier cosa, contactar con soporte.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

